// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prode5digos.domain;

import com.prode5digos.domain.Torneo;

privileged aspect Torneo_Roo_JavaBean {
    
    public String Torneo.getNombre() {
        return this.nombre;
    }
    
    public void Torneo.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
