// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prode5digos.domain;

import com.prode5digos.domain.Torneo;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Torneo_Roo_Configurable {
    
    declare @type: Torneo: @Configurable;
    
}
